=== mkarumuri-REISys/HAB-Essentials/CAT/Lib/Platform/v4.9.55_UTL7/PLConfig_Internal/Config/Platform/AsynchronousTask/schema/AsynchronousTask.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence minOccurs="1">
                <xs:element name="userId" minOccurs="0" maxOccurs="1"></xs:element>
                <xs:element name="itemRepositories">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:choice maxOccurs="unbounded">
                                <xs:element name="default">
                                    <xs:complexType>
                                        <xs:attribute name="pollInterval" type="xs:unsignedShort" use="required" />
                                        <xs:attribute name="itemTable" type="xs:string" use="required" />
                                        <xs:attribute name="itemProcessedTable" type="xs:string" use="required" />
                                        <xs:attribute name="errorTable" type="xs:string" use="required" />
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="custom">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element maxOccurs="unbounded" name="itemRepository">
                                                <xs:complexType>
                                                    <xs:attribute name="assembly" type="xs:string" use="required" />
                                                    <xs:attribute name="type" type="xs:string" use="required" />
                                                    <xs:attribute name="pollInterval" type="xs:unsignedShort" use="required" />
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="processes">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:choice>
                                <xs:element name="process">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="task" minOccurs="1" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:attribute name="input" type="xs:int" use="required" />
                                                    <xs:attribute name="output" type="xs:int" use="required" />
                                                    <xs:attribute name="assembly" type="xs:string" use="required" />
                                                    <xs:attribute name="type" type="xs:string" use="required" />
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="taskErrorHandler" minOccurs="0" maxOccurs="1">
                                                <xs:complexType>
                                                    <xs:attribute name="assembly" type="xs:string" use="required" />
                                                    <xs:attribute name="type" type="xs:string" use="required" />
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                        <xs:attribute name="processType" type="xs:int" use="required" />
                                        <xs:attribute name="maxThreads" type="xs:int" use="required" />
                                        <xs:attribute name="finalStatus" type="xs:int" use="required" />
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="continuousProcess">
                                    <xs:complexType>   
                                        <xs:sequence>
                                            <xs:element name="task" minOccurs="1" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:attribute name="assembly" type="xs:string" use="required" />
                                                    <xs:attribute name="type" type="xs:string" use="required" />
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="taskErrorHandler" minOccurs="0" maxOccurs="1">
                                                <xs:complexType>
                                                    <xs:attribute name="assembly" type="xs:string" use="required" />
                                                    <xs:attribute name="type" type="xs:string" use="required" />
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                        <xs:attribute name="processType" type="xs:int" use="required" />
                                        <xs:attribute name="interval" type="xs:time" use="required"/>
                                        <xs:attribute name="userId" type="xs:string" use="required"/>    
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xsd:schema>

=== mkarumuri-REISys/HAB-Essentials/CAT/Lib/Platform/v4.9.55/PLConfig_Internal/Config/AsynchronousTask/ProcessConfig.xml
<?xml version="1.0" encoding="utf-8" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://Y:/Workspace/Tools/REISchemas/AsynchronousTask.xsd">
  <userId>49F8AC75-5D25-4F81-86D9-48E895824257</userId>
  <itemRepositories>
    <default pollInterval="3000"
			itemTable="AsynchronousTaskItem"
		  itemProcessedTable="AsynchronousTaskCompletedItem"
			errorTable="AsynchronousTaskError"/>
  </itemRepositories>  
  <processes>
    <!--interval = hh:mm:ss-->
    <!-- <continuousProcess interval="23:59:50" processType="11" userId="49F8AC75-5D25-4F81-86D9-48E895824257"> -->
      <!-- <task assembly="REISys.LNS.LoansAsyncService" type="REISys.LNS.LoansAsyncService.NeedAnalysisTaskService"/> -->
    <!-- </continuousProcess> -->
    <process processType="40" maxThreads="1" finalStatus="2">
      <task input="1" output="2" assembly="OrhpAsynchronousService" type="OrhpAsynchronousService.ProcessPatientUpload"/>      
    </process>
    <process processType="42" maxThreads="1" finalStatus="2">
      <task input="1" output="2" assembly="OrhpAsynchronousService" type="OrhpAsynchronousService.ProcessTRCDataUpload"/>      
    </process>	
    <process processType="146" maxThreads="1" finalStatus="2">    
      <task input="1" output="2" assembly="HIVQMAsynchronousService" type="HIVQMAsynchronousService.HIVQMUpload"/>   
    </process>         
  </processes>
</root>
